# Generated by Django 5.0.2 on 2024-04-02 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_id', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('day', models.DateField(auto_now_add=True)),
                ('hour', models.TimeField(auto_now_add=True)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_incomes', to='accounts.income')),
            ],
        ),
        migrations.CreateModel(
            name='CardIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('day', models.DateField(auto_now_add=True)),
                ('hour', models.TimeField(auto_now_add=True)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_incomes', to='accounts.income')),
            ],
        ),
    ]
