# Generated by Django 5.0.2 on 2024-04-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardincome',
            name='card_id',
        ),
        migrations.RemoveField(
            model_name='cashincome',
            name='cash_id',
        ),
    ]
